//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DmsIntegrationService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DmsIntegrationService.DmsServiceSoap")]
    public interface DmsServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.AddDocumentResponse> AddDocumentAsync(DmsIntegrationService.AddDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.GetFileDataResponse> GetFileDataAsync(DmsIntegrationService.GetFileDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePageNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task UpdatePageNumAsync(string docID, int pageNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.FileInfo> GetDocumentInfoAsync(string docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAnnotation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.GetAnnotationResponse> GetAnnotationAsync(DmsIntegrationService.GetAnnotationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAnnotationObject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.GetAnnotationObjectResponse> GetAnnotationObjectAsync(DmsIntegrationService.GetAnnotationObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAnnotation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.SaveAnnotationResponse> SaveAnnotationAsync(DmsIntegrationService.SaveAnnotationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentInfoAndData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.InfoAndDataResponse> GetDocumentInfoAndDataAsync(string docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.DocumentResponse> GetDocumentAsync(string docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.UpdateFileResponse> UpdateFileAsync(DmsIntegrationService.UpdateFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> UpdateDocumentAsync(string docID, string cmdData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> DeleteDocumentAsync(string docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetMessageAsync(string msgGroup, string msgID, string msgLang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LookForDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> LookForDocumentAsync(string tagData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchForDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int[]> SearchForDocumentAsync(string tagData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchForDocumentWithMeta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> SearchForDocumentWithMetaAsync(string tagData, int pageNum, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteCmd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.ExecuteCmdResponse> ExecuteCmdAsync(DmsIntegrationService.ExecuteCmdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProvideDownloadLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ProvideDownloadLinkAsync(string docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetCustomerDocumentAsync(string customerNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerDocumentMulti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetCustomerDocumentMultiAsync(string customerNum, string langCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMetaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetMetaDataAsync(int docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatementDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetStatementDocumentAsync(string cardNum, string customerNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.GetFileResponse> GetFileAsync(DmsIntegrationService.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchForDocumentWithCreateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int[]> SearchForDocumentWithCreateTimeAsync(string tagData, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchemaList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetSchemaListAsync(string LangCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplicateReferences", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long[]> MultiplicateReferencesAsync(long DocID, string[] referenceList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTagList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetTagListAsync(string SchemaID, string LangCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTagElementList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetTagElementListAsync(string TagID, string LangCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBarcodedDocRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long> AddBarcodedDocRecordAsync(string docTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDMSDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.DMSDocument> GetDMSDocumentAsync(long docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerHasStockDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> CustomerHasStockDocAsync(string customerNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerHasDocByType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.DocReturnValues> CustomerHasDocByTypeAsync(string customerNum, int docType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentByCustomerAndTag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.InfoAndDataResponse> GetDocumentByCustomerAndTagAsync(string customerNum, string tags);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IbGetDocumentGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.IbGetDocumentGroupsResponse> IbGetDocumentGroupsAsync(DmsIntegrationService.IbGetDocumentGroupsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IbGetDocuments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.IbGetDocumentsResponse> IbGetDocumentsAsync(DmsIntegrationService.IbGetDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IbGetDocumentContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.IbGetDocumentContentResponse> IbGetDocumentContentAsync(DmsIntegrationService.IbGetDocumentContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateInsurancePolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DmsIntegrationService.UpdateInsurancePolicyResponse> UpdateInsurancePolicyAsync(DmsIntegrationService.UpdateInsurancePolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckStatementDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> CheckStatementDocumentAsync(string tagId, string accountBranchCode, string accountNumber, string accountSuffix);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDocument", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cmdData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] binaryData;
        
        public AddDocumentRequest()
        {
        }
        
        public AddDocumentRequest(string cmdData, byte[] binaryData)
        {
            this.cmdData = cmdData;
            this.binaryData = binaryData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDocumentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AddDocumentResult;
        
        public AddDocumentResponse()
        {
        }
        
        public AddDocumentResponse(string AddDocumentResult)
        {
            this.AddDocumentResult = AddDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string docID;
        
        public GetFileDataRequest()
        {
        }
        
        public GetFileDataRequest(string docID)
        {
            this.docID = docID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFileDataResult;
        
        public GetFileDataResponse()
        {
        }
        
        public GetFileDataResponse(byte[] GetFileDataResult)
        {
            this.GetFileDataResult = GetFileDataResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileInfo
    {
        
        private string serverIDField;
        
        private string libraryField;
        
        private string cabinetField;
        
        private string folderField;
        
        private string idField;
        
        private long docIDField;
        
        private string mimeTypeField;
        
        private string fileNameField;
        
        private bool isLegacyField;
        
        private System.DateTime createTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServerID
        {
            get
            {
                return this.serverIDField;
            }
            set
            {
                this.serverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Library
        {
            get
            {
                return this.libraryField;
            }
            set
            {
                this.libraryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Cabinet
        {
            get
            {
                return this.cabinetField;
            }
            set
            {
                this.cabinetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Folder
        {
            get
            {
                return this.folderField;
            }
            set
            {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long DocID
        {
            get
            {
                return this.docIDField;
            }
            set
            {
                this.docIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsLegacy
        {
            get
            {
                return this.isLegacyField;
            }
            set
            {
                this.isLegacyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime CreateTime
        {
            get
            {
                return this.createTimeField;
            }
            set
            {
                this.createTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateInsurancePolicyResponse
    {
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateInsurancePolicyRequest
    {
        
        private string customerNumberField;
        
        private string firmCodeField;
        
        private string policyNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirmCode
        {
            get
            {
                return this.firmCodeField;
            }
            set
            {
                this.firmCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PolicyNumber
        {
            get
            {
                return this.policyNumberField;
            }
            set
            {
                this.policyNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IbGetDocumentContentResponse
    {
        
        private IbDocument ibDocumentField;
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IbDocument IbDocument
        {
            get
            {
                return this.ibDocumentField;
            }
            set
            {
                this.ibDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IbDocument
    {
        
        private string docIdField;
        
        private IbTagGroup groupField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string fileExtensionField;
        
        private string mimeTypeField;
        
        private System.DateTime docDateField;
        
        private IbMetaData[] metaDataListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocId
        {
            get
            {
                return this.docIdField;
            }
            set
            {
                this.docIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IbTagGroup Group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FileExtension
        {
            get
            {
                return this.fileExtensionField;
            }
            set
            {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public IbMetaData[] MetaDataList
        {
            get
            {
                return this.metaDataListField;
            }
            set
            {
                this.metaDataListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IbTagGroup
    {
        
        private string tagIdField;
        
        private string tagNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TagId
        {
            get
            {
                return this.tagIdField;
            }
            set
            {
                this.tagIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TagName
        {
            get
            {
                return this.tagNameField;
            }
            set
            {
                this.tagNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IbMetaData
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IbGetDocumentContentRequest
    {
        
        private string customerIdField;
        
        private string documentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IbGetDocumentsResponse
    {
        
        private IbDocument[] ibDocumentListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public IbDocument[] IbDocumentList
        {
            get
            {
                return this.ibDocumentListField;
            }
            set
            {
                this.ibDocumentListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IbGetDocumentsRequest
    {
        
        private string channelField;
        
        private string customerIdField;
        
        private string tagIdField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private int pageNumField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TagId
        {
            get
            {
                return this.tagIdField;
            }
            set
            {
                this.tagIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int PageNum
        {
            get
            {
                return this.pageNumField;
            }
            set
            {
                this.pageNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IbGetDocumentGroupsResponse
    {
        
        private IbTagGroup[] tagGroupListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public IbTagGroup[] TagGroupList
        {
            get
            {
                return this.tagGroupListField;
            }
            set
            {
                this.tagGroupListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IbGetDocumentGroupsRequest
    {
        
        private string channelField;
        
        private string customerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DocReturnValues
    {
        
        private int errorCodeField;
        
        private string errorValField;
        
        private bool hasDocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorVal
        {
            get
            {
                return this.errorValField;
            }
            set
            {
                this.errorValField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool HasDoc
        {
            get
            {
                return this.hasDocField;
            }
            set
            {
                this.hasDocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DMSDocument
    {
        
        private long idField;
        
        private System.DateTime createTimeField;
        
        private string ownerIDField;
        
        private string titleField;
        
        private string notesField;
        
        private string dcField;
        
        private string channelField;
        
        private string customerNoField;
        
        private string applicationNoField;
        
        private string wfInstanceIDField;
        
        private bool isExpiredField;
        
        private string tagIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CreateTime
        {
            get
            {
                return this.createTimeField;
            }
            set
            {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OwnerID
        {
            get
            {
                return this.ownerIDField;
            }
            set
            {
                this.ownerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Dc
        {
            get
            {
                return this.dcField;
            }
            set
            {
                this.dcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerNo
        {
            get
            {
                return this.customerNoField;
            }
            set
            {
                this.customerNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ApplicationNo
        {
            get
            {
                return this.applicationNoField;
            }
            set
            {
                this.applicationNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string WfInstanceID
        {
            get
            {
                return this.wfInstanceIDField;
            }
            set
            {
                this.wfInstanceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsExpired
        {
            get
            {
                return this.isExpiredField;
            }
            set
            {
                this.isExpiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TagID
        {
            get
            {
                return this.tagIDField;
            }
            set
            {
                this.tagIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DocumentResponse
    {
        
        private string metaDataField;
        
        private FileInfo fInfoField;
        
        private byte[] binaryDataField;
        
        private byte[] annotationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MetaData
        {
            get
            {
                return this.metaDataField;
            }
            set
            {
                this.metaDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FileInfo FInfo
        {
            get
            {
                return this.fInfoField;
            }
            set
            {
                this.fInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] BinaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoAndDataResponse
    {
        
        private FileInfo fInfoField;
        
        private byte[] binaryDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FileInfo FInfo
        {
            get
            {
                return this.fInfoField;
            }
            set
            {
                this.fInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] BinaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnotation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnotationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string docID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageNum;
        
        public GetAnnotationRequest()
        {
        }
        
        public GetAnnotationRequest(string docID, int pageNum)
        {
            this.docID = docID;
            this.pageNum = pageNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnotationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnotationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetAnnotationResult;
        
        public GetAnnotationResponse()
        {
        }
        
        public GetAnnotationResponse(byte[] GetAnnotationResult)
        {
            this.GetAnnotationResult = GetAnnotationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnotationObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnotationObjectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string docID;
        
        public GetAnnotationObjectRequest()
        {
        }
        
        public GetAnnotationObjectRequest(string docID)
        {
            this.docID = docID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnotationObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnotationObjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetAnnotationObjectResult;
        
        public GetAnnotationObjectResponse()
        {
        }
        
        public GetAnnotationObjectResponse(byte[] GetAnnotationObjectResult)
        {
            this.GetAnnotationObjectResult = GetAnnotationObjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveAnnotation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveAnnotationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string docID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] annotationData;
        
        public SaveAnnotationRequest()
        {
        }
        
        public SaveAnnotationRequest(string docID, int pageNum, string userID, byte[] annotationData)
        {
            this.docID = docID;
            this.pageNum = pageNum;
            this.userID = userID;
            this.annotationData = annotationData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveAnnotationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveAnnotationResponse
    {
        
        public SaveAnnotationResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long docID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mimeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] binaryData;
        
        public UpdateFileRequest()
        {
        }
        
        public UpdateFileRequest(long docID, string fileName, string mimeType, byte[] binaryData)
        {
            this.docID = docID;
            this.fileName = fileName;
            this.mimeType = mimeType;
            this.binaryData = binaryData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateFileResult;
        
        public UpdateFileResponse()
        {
        }
        
        public UpdateFileResponse(bool UpdateFileResult)
        {
            this.UpdateFileResult = UpdateFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteCmd", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteCmdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] receivedCmd;
        
        public ExecuteCmdRequest()
        {
        }
        
        public ExecuteCmdRequest(byte[] receivedCmd)
        {
            this.receivedCmd = receivedCmd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteCmdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteCmdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExecuteCmdResult;
        
        public ExecuteCmdResponse()
        {
        }
        
        public ExecuteCmdResponse(byte[] ExecuteCmdResult)
        {
            this.ExecuteCmdResult = ExecuteCmdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tagData;
        
        public GetFileRequest()
        {
        }
        
        public GetFileRequest(string tagData)
        {
            this.tagData = tagData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFileResult;
        
        public GetFileResponse()
        {
        }
        
        public GetFileResponse(byte[] GetFileResult)
        {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DmsServiceSoapChannel : DmsIntegrationService.DmsServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DmsServiceSoapClient : System.ServiceModel.ClientBase<DmsIntegrationService.DmsServiceSoap>, DmsIntegrationService.DmsServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DmsServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DmsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), DmsServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DmsServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DmsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DmsServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DmsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DmsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DmsIntegrationService.AddDocumentResponse> DmsIntegrationService.DmsServiceSoap.AddDocumentAsync(DmsIntegrationService.AddDocumentRequest request)
        {
            return base.Channel.AddDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.AddDocumentResponse> AddDocumentAsync(string cmdData, byte[] binaryData)
        {
            DmsIntegrationService.AddDocumentRequest inValue = new DmsIntegrationService.AddDocumentRequest();
            inValue.cmdData = cmdData;
            inValue.binaryData = binaryData;
            return ((DmsIntegrationService.DmsServiceSoap)(this)).AddDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DmsIntegrationService.GetFileDataResponse> DmsIntegrationService.DmsServiceSoap.GetFileDataAsync(DmsIntegrationService.GetFileDataRequest request)
        {
            return base.Channel.GetFileDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.GetFileDataResponse> GetFileDataAsync(string docID)
        {
            DmsIntegrationService.GetFileDataRequest inValue = new DmsIntegrationService.GetFileDataRequest();
            inValue.docID = docID;
            return ((DmsIntegrationService.DmsServiceSoap)(this)).GetFileDataAsync(inValue);
        }
        
        public System.Threading.Tasks.Task UpdatePageNumAsync(string docID, int pageNum)
        {
            return base.Channel.UpdatePageNumAsync(docID, pageNum);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.FileInfo> GetDocumentInfoAsync(string docID)
        {
            return base.Channel.GetDocumentInfoAsync(docID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DmsIntegrationService.GetAnnotationResponse> DmsIntegrationService.DmsServiceSoap.GetAnnotationAsync(DmsIntegrationService.GetAnnotationRequest request)
        {
            return base.Channel.GetAnnotationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.GetAnnotationResponse> GetAnnotationAsync(string docID, int pageNum)
        {
            DmsIntegrationService.GetAnnotationRequest inValue = new DmsIntegrationService.GetAnnotationRequest();
            inValue.docID = docID;
            inValue.pageNum = pageNum;
            return ((DmsIntegrationService.DmsServiceSoap)(this)).GetAnnotationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DmsIntegrationService.GetAnnotationObjectResponse> DmsIntegrationService.DmsServiceSoap.GetAnnotationObjectAsync(DmsIntegrationService.GetAnnotationObjectRequest request)
        {
            return base.Channel.GetAnnotationObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.GetAnnotationObjectResponse> GetAnnotationObjectAsync(string docID)
        {
            DmsIntegrationService.GetAnnotationObjectRequest inValue = new DmsIntegrationService.GetAnnotationObjectRequest();
            inValue.docID = docID;
            return ((DmsIntegrationService.DmsServiceSoap)(this)).GetAnnotationObjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DmsIntegrationService.SaveAnnotationResponse> DmsIntegrationService.DmsServiceSoap.SaveAnnotationAsync(DmsIntegrationService.SaveAnnotationRequest request)
        {
            return base.Channel.SaveAnnotationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.SaveAnnotationResponse> SaveAnnotationAsync(string docID, int pageNum, string userID, byte[] annotationData)
        {
            DmsIntegrationService.SaveAnnotationRequest inValue = new DmsIntegrationService.SaveAnnotationRequest();
            inValue.docID = docID;
            inValue.pageNum = pageNum;
            inValue.userID = userID;
            inValue.annotationData = annotationData;
            return ((DmsIntegrationService.DmsServiceSoap)(this)).SaveAnnotationAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.InfoAndDataResponse> GetDocumentInfoAndDataAsync(string docID)
        {
            return base.Channel.GetDocumentInfoAndDataAsync(docID);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.DocumentResponse> GetDocumentAsync(string docID)
        {
            return base.Channel.GetDocumentAsync(docID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DmsIntegrationService.UpdateFileResponse> DmsIntegrationService.DmsServiceSoap.UpdateFileAsync(DmsIntegrationService.UpdateFileRequest request)
        {
            return base.Channel.UpdateFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.UpdateFileResponse> UpdateFileAsync(long docID, string fileName, string mimeType, byte[] binaryData)
        {
            DmsIntegrationService.UpdateFileRequest inValue = new DmsIntegrationService.UpdateFileRequest();
            inValue.docID = docID;
            inValue.fileName = fileName;
            inValue.mimeType = mimeType;
            inValue.binaryData = binaryData;
            return ((DmsIntegrationService.DmsServiceSoap)(this)).UpdateFileAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDocumentAsync(string docID, string cmdData)
        {
            return base.Channel.UpdateDocumentAsync(docID, cmdData);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDocumentAsync(string docID)
        {
            return base.Channel.DeleteDocumentAsync(docID);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string msgGroup, string msgID, string msgLang)
        {
            return base.Channel.GetMessageAsync(msgGroup, msgID, msgLang);
        }
        
        public System.Threading.Tasks.Task<bool> LookForDocumentAsync(string tagData)
        {
            return base.Channel.LookForDocumentAsync(tagData);
        }
        
        public System.Threading.Tasks.Task<int[]> SearchForDocumentAsync(string tagData)
        {
            return base.Channel.SearchForDocumentAsync(tagData);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> SearchForDocumentWithMetaAsync(string tagData, int pageNum, int pageSize)
        {
            return base.Channel.SearchForDocumentWithMetaAsync(tagData, pageNum, pageSize);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DmsIntegrationService.ExecuteCmdResponse> DmsIntegrationService.DmsServiceSoap.ExecuteCmdAsync(DmsIntegrationService.ExecuteCmdRequest request)
        {
            return base.Channel.ExecuteCmdAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.ExecuteCmdResponse> ExecuteCmdAsync(byte[] receivedCmd)
        {
            DmsIntegrationService.ExecuteCmdRequest inValue = new DmsIntegrationService.ExecuteCmdRequest();
            inValue.receivedCmd = receivedCmd;
            return ((DmsIntegrationService.DmsServiceSoap)(this)).ExecuteCmdAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> ProvideDownloadLinkAsync(string docID)
        {
            return base.Channel.ProvideDownloadLinkAsync(docID);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetCustomerDocumentAsync(string customerNum)
        {
            return base.Channel.GetCustomerDocumentAsync(customerNum);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetCustomerDocumentMultiAsync(string customerNum, string langCode)
        {
            return base.Channel.GetCustomerDocumentMultiAsync(customerNum, langCode);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetMetaDataAsync(int docID)
        {
            return base.Channel.GetMetaDataAsync(docID);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetStatementDocumentAsync(string cardNum, string customerNum)
        {
            return base.Channel.GetStatementDocumentAsync(cardNum, customerNum);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DmsIntegrationService.GetFileResponse> DmsIntegrationService.DmsServiceSoap.GetFileAsync(DmsIntegrationService.GetFileRequest request)
        {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.GetFileResponse> GetFileAsync(string tagData)
        {
            DmsIntegrationService.GetFileRequest inValue = new DmsIntegrationService.GetFileRequest();
            inValue.tagData = tagData;
            return ((DmsIntegrationService.DmsServiceSoap)(this)).GetFileAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int[]> SearchForDocumentWithCreateTimeAsync(string tagData, System.DateTime startDate, System.DateTime endDate)
        {
            return base.Channel.SearchForDocumentWithCreateTimeAsync(tagData, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetSchemaListAsync(string LangCode)
        {
            return base.Channel.GetSchemaListAsync(LangCode);
        }
        
        public System.Threading.Tasks.Task<long[]> MultiplicateReferencesAsync(long DocID, string[] referenceList)
        {
            return base.Channel.MultiplicateReferencesAsync(DocID, referenceList);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetTagListAsync(string SchemaID, string LangCode)
        {
            return base.Channel.GetTagListAsync(SchemaID, LangCode);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.ArrayOfXElement> GetTagElementListAsync(string TagID, string LangCode)
        {
            return base.Channel.GetTagElementListAsync(TagID, LangCode);
        }
        
        public System.Threading.Tasks.Task<long> AddBarcodedDocRecordAsync(string docTypeID)
        {
            return base.Channel.AddBarcodedDocRecordAsync(docTypeID);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.DMSDocument> GetDMSDocumentAsync(long docID)
        {
            return base.Channel.GetDMSDocumentAsync(docID);
        }
        
        public System.Threading.Tasks.Task<bool> CustomerHasStockDocAsync(string customerNum)
        {
            return base.Channel.CustomerHasStockDocAsync(customerNum);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.DocReturnValues> CustomerHasDocByTypeAsync(string customerNum, int docType)
        {
            return base.Channel.CustomerHasDocByTypeAsync(customerNum, docType);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.InfoAndDataResponse> GetDocumentByCustomerAndTagAsync(string customerNum, string tags)
        {
            return base.Channel.GetDocumentByCustomerAndTagAsync(customerNum, tags);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.IbGetDocumentGroupsResponse> IbGetDocumentGroupsAsync(DmsIntegrationService.IbGetDocumentGroupsRequest request)
        {
            return base.Channel.IbGetDocumentGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.IbGetDocumentsResponse> IbGetDocumentsAsync(DmsIntegrationService.IbGetDocumentsRequest request)
        {
            return base.Channel.IbGetDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.IbGetDocumentContentResponse> IbGetDocumentContentAsync(DmsIntegrationService.IbGetDocumentContentRequest request)
        {
            return base.Channel.IbGetDocumentContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DmsIntegrationService.UpdateInsurancePolicyResponse> UpdateInsurancePolicyAsync(DmsIntegrationService.UpdateInsurancePolicyRequest request)
        {
            return base.Channel.UpdateInsurancePolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task<bool> CheckStatementDocumentAsync(string tagId, string accountBranchCode, string accountNumber, string accountSuffix)
        {
            return base.Channel.CheckStatementDocumentAsync(tagId, accountBranchCode, accountNumber, accountSuffix);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DmsServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DmsServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DmsServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://svpredms01.ebt.bank/Intertech.rota.dms.appserver/dmsservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DmsServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://svpredms01.ebt.bank/Intertech.rota.dms.appserver/dmsservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DmsServiceSoap,
            
            DmsServiceSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
