apiVersion: v1
kind: Service
metadata:
  name: endorsement-worker
  namespace: bbt-endorsement
spec:
  type: LoadBalancer
  ports:
  - port: 5071
    targetPort: 5071
  selector:
    app: endorsement-workerapp
