apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: camuda-zeebe
    meta.helm.sh/release-namespace: bbt-endorsement
  labels:
    app: camunda-cloud-self-managed
    app.kubernetes.io/component: operate
    app.kubernetes.io/instance: camuda-zeebe
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operate
    app.kubernetes.io/part-of: camunda-cloud-self-managed
    app.kubernetes.io/version: 1.3.4
    helm.sh/chart: operate-0.0.21
  name: camuda-zeebe-operate-lb
  namespace: bbt-endorsement
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: camunda-cloud-self-managed
    app.kubernetes.io/component: operate
    app.kubernetes.io/instance: camuda-zeebe
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operate
    app.kubernetes.io/part-of: camunda-cloud-self-managed
    app.kubernetes.io/version: 1.3.4
    helm.sh/chart: operate-0.0.21
  sessionAffinity: None
  type: LoadBalancer
