export enum ApiPaths {
  Endorsement = 'Endorsement/endorsement',
  ApprovalDetail = 'Endorsement/approval-detail',
  ApprovalPhysicallyDocumentDetail = 'Endorsement/approval-physically-document-detail',
  EndorsementOrders = 'Endorsement/orders',
  GetForm = 'Endorsement/Forms/GetForm',
  GetFormContent = 'Endorsement/Forms/GetFormContent',
  CreateOrUpdateForm = 'Endorsement/Forms/CreateOrUpdateForm',
  ApproveOrderDocument = 'Endorsement/approve-order-document',
  MyApproval = 'Endorsement/my-approval',
  MyApprovalDetail = 'Endorsement/my-approval-detail',
  WantApproval = 'Endorsement/want-approval',
  WantApprovalDetail = 'Endorsement/want-approval-detail',
  WatchApproval = 'Endorsement/watch-approval',
  WatchApprovalDetail = 'Endorsement/watch-approval-detail',
  CancelOrder = 'Endorsement/cancel-order',
  PersonSearch = 'Endorsement/CustomerSearch',
  GetTags = 'Endorsement/Forms/GetTags',
  GetTagsFormName = 'Endorsement/Forms/GetTagsFormName',
  GetOrderFormParameters = 'Endorsement/Forms/GetOrderFormParameters',
  GetOrderFormTag = 'Endorsement/Forms/GetOrderFormTag',
  Login = 'Endorsement/Home/Login',
  GetOrderByFormId = 'Endorsement/FormDefinition/GetOrderByFormId',
  GetDocumentPdf = 'Endorsement/get-document-pdf',
  Preview = 'Endorsement/Forms/preview-pdf',
}
