export enum ApiPaths {
  Endorsement = 'Endorsement/endorsement',
  ApprovalDetail = 'Endorsement/approval-detail',
  ApprovalPhysicallyDocumentDetail = 'Endorsement/approval-physically-document-detail',
  EndorsementOrders = 'Endorsement/orders',
  GetForm = 'Forms/GetForm',
  GetFormContent = 'Forms/GetFormContent',
  CreateOrUpdateForm = 'Forms/CreateOrUpdateForm',
  ApproveOrderDocument = 'Endorsement/approve-order-document',
  MyApproval = 'Endorsement/my-approval',
  MyApprovalDetail = 'Endorsement/my-approval-detail',
  WantApproval = 'Endorsement/want-approval',
  WantApprovalDetail = 'Endorsement/want-approval-detail',
  WatchApproval = 'Endorsement/watch-approval',
  WatchApprovalDetail = 'Endorsement/watch-approval-detail',
  CancelOrder = 'Endorsement/cancel-order',
  PersonSearch = 'Person/person-search',
  GetTags = 'Forms/GetTags',
  GetTagsFormName = 'Forms/GetTagsFormName',
  GetOrderFormParameters = 'Forms/GetOrderFormParameters',
}
