apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: zeebe-monitor
  name: zeebe-simple-monitor
  namespace: bbt-endorsement
spec:
  clusterIP: 10.0.129.20
  clusterIPs:
  - 10.0.129.20
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31377
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: zeebe-monitor
  sessionAffinity: None
  type: LoadBalancer
