apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: zeebe-monitor
  name: zeebe-simple-monitor
  namespace: bbt-endorsement
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zeebe-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zeebe-monitor
    spec:
      containers:
      - image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.3.0
        imagePullPolicy: IfNotPresent
        name: zeebe-monitor
        ports:
        - containerPort: 8082
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/resources/application.yaml
          name: config-volume
          subPath: application.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: zeebe-simple-monitor-application-config
        name: config-volume
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
