name: CI-CD-API
on:
  push:
    branches: [ main ]
    paths:
      - 'src/Api/**'
      - 'src/Application/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/Api/**'
      - 'src/Application/**'
  workflow_dispatch:

env:
  APP_NAME: bbt.endorsement
  NAMESPACE: bbt-endorsement
  CLUSTER_NAME: Endorsement
  CLUSTER_RESOURCE_GROUP: Endorsement_group
  SECRET: docker-hub

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
 
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high  --all-projects --detection-level=2
          
      - name: Replace DB Secret
        run: |
          sed -i -e "s/DEFAULT_CONNECTION/${{ secrets.DEFAULT_CONNECTION }}/g" ./src/Api/appsettings.json
          cat ./src/Api/appsettings.json
          
      - name: Replace LOGDB Secret
        run: |
          sed -i -e "s/DEFAULT_CONNECTION_LOG/${{ secrets.DEFAULT_CONNECTION_LOG }}/g" ./src/Api/appsettings.json
          cat ./src/Api/appsettings.json
      
      - name: Replace Zeebe Gateway Secret
        run: |
          sed -i -e "s/ZEEBE_GATEWAY/${{ secrets.ZEEBE_GATEWAY }}/g" ./src/Api/appsettings.json
          cat ./src/Api/appsettings.json
          
      - name: Replace Elasticsearch Secret
        run: |
          sed -i -e "s/ELASTIC_SEARCH/${{ secrets.ELASTIC_SEARCH }}/g" ./src/Api/appsettings.json
          cat ./src/Api/appsettings.json
                    
      - name: Replace INTERNALS Secret
        run: |
          sed -i -e "s/INTERNALS/${{ secrets.INTERNALS }}/g" ./src/Api/appsettings.json
          cat ./src/Api/appsettings.json
                    
      - name: Replace TEMPLATE_ENGINE Secret
        run: |
          sed -i -e "s/TEMPLATE_ENGINE/${{ secrets.TEMPLATE_ENGINE }}/g" ./src/Api/appsettings.json
          cat ./src/Api/appsettings.json
                    
      - name: Replace SECURITYKEY Secret
        run: |
          sed -i -e "s/SECURITYKEY/${{ secrets.SECURITYKEY }}/g" ./src/Api/appsettings.json
          cat ./src/Api/appsettings.json
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}

      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
      # Create namespace if doesn't exist
      - run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -
    
      # Create image pull secret for Docker
      - uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: docker.io
          container-registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          container-registry-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          secret-name: ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
          arguments: --force true

      # Deploy app to AKS
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ${{ github.workspace }}/manifests/Api/deployment.yaml
            ${{ github.workspace }}/manifests/Api/service.yaml
          # ${{ github.workspace }}/manifests/Api/ingress.yaml
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
