name: CI-CD-UI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/Ui/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/Ui/**'
  workflow_dispatch:

env:
  APP_NAME: bbt-endorsement-ui
  NAMESPACE: bbt-endorsement
  CLUSTER_NAME: Endorsement
  CLUSTER_RESOURCE_GROUP: Endorsement_group
  SECRET: docker-hub

jobs:
  ci-cd-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace ENDORSEMENTAPI Secret
        run: |
          sed -i -e "s/ENDORSEMENTAPI/${{ secrets.ENDORSEMENTAPI }}/g" ./src/Ui/src/environments/environment.ts
          cat ./src/Ui/src/environments/environment.ts
          
      - name: Replace ENDORSEMENTAPI Secret TEST
        run: |
          sed -i -e "s/ENDORSEMENTAPI/${{ secrets.ENDORSEMENTAPI }}/g" ./src/Ui/src/environments/environment.test.ts
          cat ./src/Ui/src/environments/environment.test.ts
                         
      - name: Replace ENDORSEMENTAPI Secret UAT
        run: |
          sed -i -e "s/ENDORSEMENTAPI/${{ secrets.ENDORSEMENTAPI }}/g" ./src/Ui/src/environments/environment.uat.ts
          cat ./src/Ui/src/environments/environment.uat.ts
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high  --all-projects --detection-level=2
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Ui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}

      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
      # Create namespace if doesn't exist
      - run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -
    
      # Create image pull secret for Docker
      - uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: docker.io
          container-registry-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          container-registry-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          secret-name: ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
          arguments: --force true

      # Deploy app to AKS
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ${{ github.workspace }}/manifests/Ui/deployment.yaml
            ${{ github.workspace }}/manifests/Ui/service.yaml
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
